import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {API, graphqlOperation} from "aws-amplify";

import {listTodos} from "../src/graphql/queries";
import {createTodo, deleteTodo,updateTodo} from "../src/graphql/mutations";
import {useEffect, useState} from "react";
import classNames from "classnames";
import {ListTodos, Todo} from '../src/graphql/types';

const Home: NextPage = () => {
    const [todos, setTodos] = useState<Todo[]>([]);
    const [count, setCount] = useState(0);

    useEffect(() => {
        console.log("useEffect");
        fetchTodos();
    }, [count]);

    const fetchTodos = async () => {
        try {
            const todoData = await API.graphql(graphqlOperation(listTodos)) as ListTodos;
            const todos = todoData.data.listTodos.items.sort((a: Todo, b: Todo) =>
                Date.parse(b.createdAt) - Date.parse(a.createdAt)
            )
            setTodos(todos);
            setCount(todos.length);
        } catch (e) {
            console.error(e);
        }
    }

    const btnDelete = async (id: string) => {
        try {
            await API.graphql(graphqlOperation(deleteTodo, {input: {id}}));
            setCount(count - 1);
        } catch (e) {
            console.error(e);
        }

    }

    const btnAddClick = async () => {
        console.log(todos);
        const suffix = todos.length + 1;
        const todo = {
            name: `todo${suffix}`,
            description: `description${suffix}`,
        }
        try {
            await API.graphql(graphqlOperation(createTodo, {input: todo}));
            setCount(count + 1);
        } catch (e) {
            console.error(e);
        }

    }

    const btnUpdate = async (todo: Todo) => {
        const suffix = todo.name.length;
        const todoUpdate = {
            id: todo.id,
            name: `${todo.name} - ${suffix}`,
            description: `${todo.description} - ${suffix}`,
        }

        try {
            await API.graphql(graphqlOperation(updateTodo, {input: todoUpdate}));
            setCount(todos.length + 1)
        } catch (e) {
            console.error(e);
        }
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
                <div>
                    <button onClick={btnAddClick}>Add</button>
                </div>
                <hr/>
                {
                    todos && todos.map((todo, index) => {
                            return (
                                <div key={index} className={classNames('card', 'm-3', 'p-3')}>
                                    <h3>{todo.name}</h3>
                                    <p>{todo.description}</p>
                                    <button className={classNames('btn')} onClick={() => {
                                        btnUpdate(todo)
                                    }}>update
                                    </button>
                                    <button className={classNames('btn')} onClick={() => {
                                        btnDelete(todo.id)
                                    }}>delete
                                    </button>
                                </div>
                            )
                        }
                    )}
            </main>


        </div>
    )
}

export default Home
